/**
 * The Coin That Never Lands
 * Generated by Riddle Finder Agent
 * Source: Original - Quantum existential philosophy meets decision theory
 * Date: 2025-12-08
 */

export const riddle = {
    id: 'the-coin-that-never-lands',
    title: 'The Coin That Never Lands',
    text: `I spin between the faces of two truths,
neither false nor real until you look.
The king who rules all kingdoms yet unborn,
the prisoner freed before the lock.

I am the third child of a binary star,
the answer hiding in the question's seam.
The bridge that only exists while crossed,
the waking moment trapped inside the dream.

I hold more power in my flight than landed,
for I am every outcome and none.
The debt that's paid by never being settled,
the race that's won by never being run.

Tell me: am I the choice, or choice's death?
The freedom or the weight of waiting's breath?

And when you call my name, do I collapse,
or multiply in infinite perhaps?`,
    correctAnswers: [
        'potential',
        'possibility',
        'potentiality',
        'the potential',
        'the possible',
        'uncertainty',
        'superposition',
        'quantum superposition',
        'indeterminacy',
        'the unresolved',
        'undecided',
        'the undecided'
    ],
    closeAnswers: [
        'choice',
        'decision',
        'probability',
        'chance',
        'fate',
        'future',
        'unknown',
        'doubt',
        'paradox',
        'schrodinger',
        'quantum',
        'limbo',
        'indecision',
        'hesitation',
        'ambiguity',
        'options',
        'alternatives'
    ],
    hints: [
        'Think about a state that exists before resolution',
        'Consider what holds more power: the locked box or the opened one?',
        'This exists in the space between yes and no',
        'Quantum mechanics has a famous concept about cats and boxes',
        'It is all things until it becomes one thing',
        'The answer is what you lose the moment you make a decision',
        'Think about what exists in the "spin" before the coin lands',
        'It is the realm of "could be" rather than "is"'
    ],
    wrongAnswerFeedback: 'Not quite. Consider what exists before something becomes definite...',
    closeAnswerFeedback: 'You are very close! Think about the state that precedes your answer.',
    explanation: 'Potential is the quantum state of unlimited possibility that exists before observation, decision, or resolution. It "spins between two truths" like a coin in flight - neither heads nor tails until it lands. It is "the king who rules all kingdoms yet unborn" because potential contains every possible outcome simultaneously. The "third child of a binary star" refers to the superposition state that transcends binary thinking. Potential holds "more power in flight than landed" because once potential becomes actual, all other possibilities collapse. The coin metaphor references both decision theory and quantum superposition - Schrödinger\'s cat is simultaneously alive and dead in potential until observed. The final paradox asks: when you name potential and make it actual, does it die (collapse into one reality) or does it spawn infinite new potentials? This riddle can be read as psychological (the anxiety of choice), physical (quantum mechanics), philosophical (actualism vs possibilism), or existential (the terror and freedom of unlimited possibility).',
    answer: 'Potential'
};
