/**
 * The Clockmaker's Child
 * Generated by Riddle Finder Agent
 * Source: Original - Multi-interpretive philosophical riddle
 * Date: 2025-12-08
 */

export const riddle = {
    id: 'the-clockmakers-child',
    title: 'The Clockmaker\'s Child',
    text: `I count the hours my father never lived,
I wear the scar he gave before my birth.
Each tick I make erases what he built,
each tock reveals the measure of my worth.

I am the number that divides itself,
the child who parents those who came before.
I keep the time that no one can possess,
and break the lock on every bolted door.

The birds who nest within my hollow chest
sing only songs of futures that have passed.
I feed on moments, growing ever thin,
the first to finish, always born the last.

Tell me: am I the maker or the made?
The wound that heals, or blade that cuts the blade?

And when I stop, do I begin again?
Or am I just the space between the when?`,
    correctAnswers: [
        'recursion',
        'recursive function',
        'loop',
        'cycle',
        'iteration',
        'recursive loop',
        'infinite loop',
        'self-reference',
        'recursive process',
        'feedback loop',
        'recursion algorithm',
        'cyclical process'
    ],
    closeAnswers: [
        'time',
        'clock',
        'clockwork',
        'algorithm',
        'code',
        'program',
        'automation',
        'function',
        'process',
        'system',
        'machine',
        'inheritance',
        'evolution',
        'generation',
        'legacy',
        'fate',
        'destiny',
        'history',
        'future',
        'paradox',
        'ouroboros'
    ],
    hints: [
        'Think about something that refers to itself',
        'Consider a process that contains itself within itself',
        'It is both the child and the parent of its own existence',
        'This concept exists in mathematics, programming, and nature',
        'Each iteration creates the conditions for the next',
        'It counts itself by running itself',
        'The answer involves a process that calls itself to complete itself',
        'What creates itself by unmaking and remaking endlessly?'
    ],
    wrongAnswerFeedback: 'Not quite. Think about processes that contain themselves, that are both creator and creation...',
    closeAnswerFeedback: 'You\'re very close! Consider the specific mechanism of self-reference and repetition.',
    explanation: 'Recursion is the clockmaker\'s child - a function that calls itself, counting iterations its "father" (the original call) never completed. It wears the "scar" of its base case, the condition that existed before it began. Each recursive call "erases what he built" by unwinding the stack, while simultaneously revealing its worth through computation. It is "the number that divides itself" - mathematically breaking problems into smaller versions of themselves. It "parents those who came before" because each recursive call creates the context for previous calls to resolve. It keeps time (tracks state) that no one can possess (exists only in execution). The "birds in hollow chest" are the stack frames - futures (pending calls) that represent pasts (completed work). It "feeds on moments" (consumes stack space) while growing thin (approaching base case). Born last (deepest call) but finishes first (returns first). The paradox: is recursion the function that calls, or the function being called? The wound that heals (resolves) or the blade that cuts itself (infinite recursion)? When it stops, does it begin again (tail recursion) or is it merely the conceptual space between iterations?',
    answer: 'Recursion'
};
