/**
 * The Clockmaker's Unborn
 * Generated by Riddle Finder Agent
 * Source: Original - Multi-interpretive symbolic riddle
 * Date: 2025-12-08
 */

export const riddle = {
    id: 'the-clockmaker-unborn',
    title: 'The Clockmaker\'s Unborn',
    text: `I count the seconds that never were,
the hours buried beneath the scar.
My hands turn backward, forward, still—
a prophecy that breaks its will.

The number speaks but has no mouth,
it points to East, then spins to South.
I am the child the clock refused,
the zero sum that can't be used.

They wind me up to make me rest,
they read my face but miss the test.
I am the answer that questions you,
the false start written in what's true.

Tell me: am I the time or the keeper?
The wound that counts, or the one who's deeper?

What number am I, that holds the breach—
the tick that stops, the moment each?`,
    correctAnswers: [
        'zero',
        'the number zero',
        'nothing',
        'nothingness',
        'absence',
        'void',
        'the void',
        'emptiness',
        'null'
    ],
    closeAnswers: [
        'infinity',
        'time',
        'placeholder',
        'beginning',
        'end',
        'death',
        'reset',
        'midnight',
        'origin',
        'one',
        'negative number',
        'cipher'
    ],
    hints: [
        'Think about what exists between existence and non-existence',
        'Consider a number that is both powerful and powerless',
        'It\'s something that counts but represents the absence of counting',
        'Clocks use this to mark beginnings and endings',
        'Mathematically, it\'s neither positive nor negative',
        'It was once refused by many cultures but is now essential',
        'The answer is a number that represents "nothing" but changes everything',
        'Without this concept, modern mathematics and computing would collapse'
    ],
    wrongAnswerFeedback: 'Not quite. Think about what the clock shows at the moment of reset...',
    closeAnswerFeedback: 'You\'re circling the truth! Consider what makes all these concepts possible.',
    explanation: 'Zero is "the clockmaker\'s unborn"—it exists but represents absence. It counts seconds that never were (counting from nothing). Zero\'s discovery was revolutionary: ancient cultures feared and rejected it, calling it "the child the clock refused." In mathematics, zero is paradoxical: multiplying by it destroys value ("zero sum"), yet it\'s essential for positional notation. Clocks reset to zero, making it both an ending and beginning. Zero is "the number that speaks but has no mouth"—it has meaning but represents nothing. Philosophically, it\'s the wound that counts (trauma, absence, loss) and the breach in continuity. Technologically, it\'s fundamental to binary code (0 and 1). Religiously, it echoes concepts of void, creation ex nihilo. Politically, it represents the year zero, historical erasure, or reset. Zero is the false start written in truth—essential despite being nothing.',
    answer: 'Zero'
};
