/**
 * The Archive of Silence
 * Generated by Riddle Finder Agent
 * Source: Original - Multi-interpretive philosophical riddle
 * Date: 2025-12-08
 */

export const riddle = {
    id: 'the-archive-of-silence',
    title: 'The Archive of Silence',
    text: `I am the door that opens when you close your mouth,
the library where every book is blank.
I hold more weight than mountains made of sound,
yet I slip through fingers, leave no mark.

The scar upon the tongue that never healed,
the number that comes before the first.
I am the treaty written in invisible ink,
the oath that breaks before it's versed.

I birth the meanings that words cannot bear,
I am the space between what's said and heard.
The king who rules by never taking throne,
the loudest truth without a single word.

Tell me: am I the answer or the question's death?
The fullness or the hollow breath?

And if you speak my name, have I not fled?
Am I the living silence, or the silence dead?`,
    correctAnswers: [
        'silence',
        'the silence',
        'absence',
        'the unspoken',
        'unsaid',
        'the void',
        'emptiness',
        'nothing',
        'nothingness',
        'quietude',
        'stillness'
    ],
    closeAnswers: [
        'peace',
        'quiet',
        'space',
        'pause',
        'gap',
        'rest',
        'calm',
        'meditation',
        'contemplation',
        'thought',
        'meaning',
        'language',
        'words',
        'communication'
    ],
    hints: [
        'Think about what exists in the absence of something',
        'Consider what happens between spoken words',
        'It\'s both nothing and everything at once',
        'This concept has power precisely because it is not present',
        'What is the "space" that gives words their meaning?',
        'The answer is what you create when you stop speaking',
        'It\'s the container that holds all possible meanings',
        'What did monks seek in their vows, and what do we fear in conversation?'
    ],
    wrongAnswerFeedback: 'Not quite. Think about what exists in absence, not presence...',
    closeAnswerFeedback: 'You\'re very close! Consider the essence of emptiness itself.',
    explanation: 'Silence is the paradoxical force that gives meaning to sound and speech. It is the "door that opens when you close your mouth" - communication happens not just through words, but through their absence. The "library where every book is blank" represents infinite potential meaning before words limit it. Silence carries "more weight than mountains made of sound" because what is unsaid often speaks louder than what is spoken. It is "the scar upon the tongue" - the words we wish we had said or are glad we didn\'t. It is "the number before the first" - the zero, the void from which all else emerges. Silence is "the space between what\'s said and heard" - the interpretive gap where true understanding (or misunderstanding) lives. The final paradox: naming silence breaks it, yet we must name it to acknowledge its power.',
    answer: 'Silence'
};
