/**
 * The River That Remembers
 * Generated by Riddle Finder Agent
 * Source: Original - Multi-interpretive philosophical riddle
 * Date: 2025-12-07
 */

export const riddle = {
    id: 'the-river-that-remembers',
    title: 'The River That Remembers',
    text: `I flow but never move,
I hold what cannot be held.
The birds that drink from me are gone,
yet their song remains, unquelled.

I carve the scar that heals itself,
I bear the weight of stones that drown.
The child who crossed me once is old,
but wears my water like a crown.

I am the thief who gives back more,
the debt that grows by being paid.
The first voice and the last silence,
the light in every shade.

Tell me: am I the river or the shore?
The wound, the hand, or what came before?

And if you name me, will I stay,
or will I vanish like the day?`,
    correctAnswers: [
        'memory',
        'memories',
        'remembering',
        'remembrance',
        'recollection',
        'the past',
        'time remembered',
        'lived experience'
    ],
    closeAnswers: [
        'time',
        'history',
        'experience',
        'consciousness',
        'thought',
        'mind',
        'nostalgia',
        'the mind',
        'thoughts',
        'dreams',
        'life'
    ],
    hints: [
        'Consider something that flows through you without moving',
        'Think about what makes birds\' songs last after they\'re gone',
        'It\'s something that creates and heals wounds simultaneously',
        'The child and the old person share this, but experience it differently',
        'It\'s both a thief and a generous giver',
        'This grows stronger when you "pay" attention to it',
        'What carries voices from the past into the present?',
        'The answer is something everyone has but experiences uniquely'
    ],
    wrongAnswerFeedback: 'Not quite. Consider what flows through consciousness without being physical...',
    closeAnswerFeedback: 'You\'re very close! Think about the personal, lived dimension of your answer.',
    explanation: 'Memory flows like a river but doesn\'t physically move. It holds experiences that can\'t be physically grasped. Birds represent fleeting moments, but their songs (memories) remain. Memory carves emotional scars that can heal over time. A child\'s memories shape who they become as an adult, wearing memories "like a crown." Memory is paradoxical: it steals the present moment but gives back richer experiences. The more you remember (pay attention), the more memories you create. Memory is both the first awareness and the last thing we hold onto.',
    answer: 'Memory'
};
